import matplotlib.pyplot as plt
import numpy as np
import transmisor
from scipy.signal import butter, filtfilt

fs = 10000           # Frecuencia de muestreo (Hz)
T = 1             # Duración total (s)
f_c = 300           # Frecuencia de la portadora (Hz)
f_m = 10  # 10 Hz
t = np.linspace(0, T, int(fs*T), endpoint=False)

def demodulateSignal(signal, frequency, phase):
    c_t = 2*np.cos(2 * np.pi * frequency * t + phase)
    return signal * c_t
#Recibo la señal y le simulo un ruido blanco en la misma
noise = np.random.normal(0, .1, transmisor.señalModuladaCF().shape)
s_t = transmisor.señalModuladaCF() + noise

S_f = np.fft.fft(s_t)
S_f = np.abs(S_f) / len(s_t)
freqs = np.fft.fftfreq(len(s_t), 1/fs)

# Creo y aplico un filtro pasabanda centrado en la frecuencia de la portadora
lowcut = f_c - f_m  # 290 Hz
highcut = f_c + f_m # 310 Hz

order = 1
b, a = butter(order, [lowcut/(fs/2), highcut/(fs/2)], btype='band')

s_t_filtered = filtfilt(b, a, s_t)

S_f_filtered = np.fft.fft(s_t_filtered)
S_f_filtered = np.abs(S_f_filtered) / len(s_t_filtered)

plt.figure(figsize=(12,8))
plt.subplot(3,1,1)
plt.plot(t, s_t)
plt.title("s(t) con ruido")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()

plt.subplot(3,1,2)
plt.plot(freqs, S_f)
plt.title("S(f) con ruido")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()

# Gráfica del espectro de la señal filtrada
plt.subplot(3,1,3)
plt.plot(t, s_t_filtered)
plt.title("s(t) con ruido con filtro pasabanda")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.show()

# Genero la señal de portadora a la frecuencia definida por f_c
m_t = demodulateSignal(s_t_filtered, f_c, 0)

M_f = np.fft.fft(m_t)
M_f = np.abs(M_f) / len(m_t)

plt.subplot(2,1,1)
plt.plot(t, m_t)
plt.title("m(t) con ruido y filtro pasabanda")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
# Gráfica del espectro de la señal filtrada
plt.subplot(2,1,2)
plt.plot(freqs, M_f)
plt.title("Espectro de la señal AM filtrada (pasabanda)")
plt.xlabel("Frecuencia [Hz]")
plt.ylabel("Magnitud")
plt.grid(True)
plt.tight_layout()
plt.show()
# Filtro pasabajo para extraer la señal de mensaje
def filtro_pasabajo(data, cutoff, fs, orden=5):
    nyq = fs / 2
    b, a = butter(orden, cutoff / nyq, btype='low')
    return filtfilt(b, a, data)

#Creo y aplico filtro pasabajo 
cutoff = f_m + 20
m_t_recovered = filtro_pasabajo(m_t, cutoff, fs)

#Mensaje Recuperado
plt.plot(t, m_t_recovered)
plt.title("m(t) Mensaje Recuperado")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.show()


m_t1 = demodulateSignal(s_t_filtered, f_c-50, 0)
m_t2 = demodulateSignal(s_t_filtered, f_c+200, 0)
m_t3 = demodulateSignal(s_t_filtered, f_c+700, 0)

M_f = np.fft.fft(m_t)
M_f = np.abs(M_f) / len(m_t)
M_f1 = np.fft.fft(m_t1)
M_f1 = np.abs(M_f1) / len(m_t1)
M_f2 = np.fft.fft(m_t2)
M_f2 = np.abs(M_f2) / len(m_t2)
M_f3 = np.fft.fft(m_t3)
M_f3 = np.abs(M_f3) / len(m_t3)
plt.subplot(4,1,1)
plt.plot(freqs, M_f)
plt.title("M(f) con oscilador a 300Hz")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,2)
plt.plot(freqs, M_f1)
plt.title("M(f) con oscilador a 350Hz")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,3)
plt.plot(freqs, M_f2)
plt.title("M(f) con oscilador a 500Hz")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,4)
plt.plot(freqs, M_f3)
plt.title("M(f) con oscilador a 1000Hz")
plt.xlabel("f")
plt.ylabel("M")
plt.ylabel("Magnitud")
plt.grid(True)
plt.tight_layout()
plt.show()
#----------------------------------------------------------
plt.subplot(4,1,1)
plt.plot(t, m_t)
plt.title("m(t) con oscilador 300Hz")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,2)
plt.plot(t, m_t1)
plt.title("m(t) con oscilador 350Hz")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,3)
plt.plot(t, m_t2)
plt.title("m(t) con oscilador 500Hz")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,4)
plt.plot(t, m_t3)
plt.title("m(t) con oscilador 1000Hz")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.show()
m_t4 = demodulateSignal(s_t_filtered, f_c, np.pi/2)
m_t5 = demodulateSignal(s_t_filtered, f_c, np.pi)
m_t6 = demodulateSignal(s_t_filtered, f_c, (3/2)*np.pi)
M_f4 = np.fft.fft(m_t4)
M_f4 = np.abs(M_f4) / len(m_t4)
M_f5 = np.fft.fft(m_t6)
M_f5 = np.abs(M_f5) / len(m_t5)
M_f6 = np.fft.fft(m_t6)
M_f6 = np.abs(M_f6) / len(m_t6)
plt.subplot(4,1,1)
plt.plot(t, m_t)
plt.title("m(t) recibido")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,2)
plt.plot(t, m_t4)
plt.title("m(t) con oscilador desafasado en π/2")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,3)
plt.plot(t, m_t5)
plt.title("m(t) con oscilador desafasado en π")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,4)
plt.plot(t, m_t6)
plt.title("m(t) con oscilador desafasado en (3/2)π")
plt.xlabel("t")
plt.ylabel("A")
plt.grid(True)
plt.tight_layout()
plt.show()
#----------------------------------------------------------------------------
plt.subplot(4,1,1)
plt.plot(freqs, M_f)
plt.title("M(f) recibido")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,2)
plt.plot(freqs, M_f4)
plt.title("m(t) con oscilador desafasado en π/2")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,3)
plt.plot(freqs, M_f5)
plt.title("m(t) con oscilador desafasado en π")
plt.xlabel("f")
plt.ylabel("M")
plt.grid(True)
plt.tight_layout()
plt.subplot(4,1,4)
plt.plot(freqs, M_f6)
plt.title("m(t) con oscilador desafasado en (3/2)π")
plt.xlabel("f")
plt.ylabel("M")
plt.ylabel("Magnitud")
plt.grid(True)
plt.tight_layout()
plt.show()
